version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: botsCrew
      POSTGRES_PASSWORD: botsCrew
      POSTGRES_DB: botsCrew_db
    volumes:
    - ./src/main/resources:/docker-entrypoint-initdb.d